apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwiz-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwiz-front
  template:
    metadata:
      labels:
        app: kwiz-front
    spec:
      containers:
      - name: kwiz-front
        image: anthonypab/kwiz_front:v1.1-release
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kwiz-front
spec:
  selector:
    app: kwiz-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kwiz-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: kwiz-game.test
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kwiz-front
                port:
                  number: 80